name: feature-workflow
on: [push]
  # workflow_dispatch button usually appears only when the
  # workflow exists in the repository’s default branch (often main or master) on GitHub
jobs:
  feature-pipeline:
    #if: github.ref_name == 'feature*' it literally comprares the same value
    #on:
      # push:
      #  branches:
      #   - feature-* here use like this
    if: startsWith(github.ref_name, 'feature-')
    uses: mrudulamangisetty/workflows/.github/workflows/nodejs-feature-pipeline.yaml@main
    with:
      project: 'roboshop'
      component: 'catalogue' 
      #environment: 'dev'
    secrets: inherit  
          # to access screts from github and pass to shrd library      
        # secrets:  ---- to acess specific secrets
        # /*-AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

